server:
  port: 8080

spring:
  application:
    name: ai-library-team1

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.postgresql.Driver
      #    url: jdbc:postgresql://10.116.64.13:8000/team1-library?stringtype=unspecified&reWriteBatchedInserts=true # 내부망(랜선)
    url: jdbc:postgresql://s3.java21.net:8000/team1-library?stringtype=unspecified&reWriteBatchedInserts=true # 외부망 (와이파이)
    username: team1
    password: ${POSTGRESQL_PW}
    dbcp2:
      initial-size: 5
      max-total: 5
      max-idle: 5
      min-idle: 5
      test-on-borrow: true
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-open-prepared-statements: 100

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  ai:
    openai:
      base-url: https://emb.java21.net
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: bge-m3
    google:
      genai:
        api-key: ${GEMINI_API_KEY} # 환경변수 사용 (.env에서 관리)
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.7
    ollama:
      base-url: http://ollama.java21.net # 올라마 서버 주소
      chat:
        options:
          model: qwen2.5:latest # 사용할 모델
          temperature: 0.3 # 응답 일관성
#          max-tokens: 1024
          top-p: 0.9
          top-k: 40

    mcp:
      client:
        enabled: true
        sse:
          connections:
            data4library:
              url: http://localhost:8081/sse

init:
  book-file: data/BOOK_DB_202112_filled.csv
  enable: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    enabled: false
    username: T1AILibBot