spring:
  application:
    name: ai-library-team1

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://s3.java21.net:8000/team1-library?stringtype=unspecified&reWriteBatchedInserts=true
    username: team1
    password: ${POSTGRESQL_PW}
    dbcp2:
      initial-size: 5
      max-total: 5
      max-idle: 5
      min-idle: 5
      test-on-borrow: true
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-open-prepared-statements: 100

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  ai:
    openai:
      base-url: https://emb.java21.net
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: bge-m3
    google:
      genai:
        api-key: ${GEMINI_API_KEY} # 환경변수 사용 (.env에서 관리)

init:
  book-file: data/BOOK_DB_202112_filled.csv
  enable: false

